import type { Theme } from "./types";
import { broadsheetTheme } from "./broadsheet";
import { minimalistTheme } from "./minimalist";
import { kidsTheme } from "./kids";
import { cyberpunkTheme } from "./cyberpunk";
import { chalkboardTheme } from "./chalkboard";
import { casinoTheme } from "./casino";

/**
 * Theme registry (COMPLETE — theme authors do not edit this file).
 * All 6 themes are registered. Each lives in its own isolated folder under
 * `src/themes/<id>/`, so parallel authors never touch a shared file.
 */
export const THEMES: Theme[] = [
  broadsheetTheme,
  minimalistTheme,
  kidsTheme,
  cyberpunkTheme,
  chalkboardTheme,
  casinoTheme,
];

export const DEFAULT_THEME_ID = "broadsheet";

export function getTheme(id: string | null | undefined): Theme {
  return THEMES.find((t) => t.id === id) ?? broadsheetTheme;
}

export { type Theme } from "./types";
export { applyTheme } from "./types";
