import type { Theme } from "./types";
import { broadsheetTheme } from "./broadsheet";
import { minimalistTheme } from "./minimalist";
import { kidsTheme } from "./kids";
import { cyberpunkTheme } from "./cyberpunk";
import { chalkboardTheme } from "./chalkboard";
import { casinoTheme } from "./casino";

/**
 * Theme registry (COMPLETE — theme authors do not edit this file).
 * All 6 themes are registered. Each lives in its own isolated folder under
 * `src/themes/<id>/`, so parallel authors never touch a shared file.
 *
 * WHOLE-PAGE THEME HOOKS (`TableOfContents`, `Dashboard`) are OPTIONAL. A theme
 * opts in by adding a component in its own folder and wiring it in its own
 * `src/themes/<id>/index.ts(x)` (e.g. `Dashboard: BroadsheetDashboard`). Until a
 * theme provides one, the page falls back to the shared BASE renderer
 * (`BaseTableOfContents` / `BaseDashboard`), so EVERY theme currently DEFAULTS
 * TO BASE for the Dashboard. Per-theme dashboards live at
 * `src/themes/<id>/Dashboard.tsx` for the 6 ids below:
 *   broadsheet, minimalist, kids, cyberpunk, chalkboard, casino.
 */
export const THEMES: Theme[] = [
  broadsheetTheme,
  minimalistTheme,
  kidsTheme,
  cyberpunkTheme,
  chalkboardTheme,
  casinoTheme,
];

export const DEFAULT_THEME_ID = "broadsheet";

export function getTheme(id: string | null | undefined): Theme {
  return THEMES.find((t) => t.id === id) ?? broadsheetTheme;
}

export { type Theme } from "./types";
export { applyTheme } from "./types";
