/**
 * gen-fixture.mjs — regenerate `scoring.fixture.json` from `scoring.mjs`.
 *
 * The fixture is the shared source of truth that pins the deterministic stream
 * and the authoritative re-score for a fixed (seed, preset, answers). BOTH the
 * server (`scoring.mjs`, which this script imports) and the client (the
 * TypeScript `rescore.test.ts`, which imports the emitted JSON) are asserted
 * against it, so the two implementations can never silently diverge.
 *
 * Run from the app root:  node infra/lambda/leaderboard/gen-fixture.mjs
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { arenaQuestionStream, rescore } from "./scoring.mjs";

const here = dirname(fileURLToPath(import.meta.url));

const preset = {
  mode: "optiver",
  durationSec: 480,
  questionCap: 12,
  penalty: true,
  skipsFree: true,
  ops: ["add", "sub", "mul", "div"],
  packs: ["int"],
  ranges: { add: [2, 100], sub: [2, 100], mul: [2, 12], div: [2, 12] },
};

const seed = 1234567;
const stream = arenaQuestionStream(seed, preset);

// Deterministic play: correct on even index, wrong on odd, skip every 5th.
const answers = stream.map((item, i) => {
  if (i % 5 === 4) return { id: item.id, value: null, rtMs: 1200 };
  const value = i % 2 === 0 ? item.answer : item.answer + 1;
  return { id: item.id, value, rtMs: 2500 + i * 50 };
});

const input = {
  board: "optiver",
  seed,
  preset,
  answers,
  clientElapsedMs: 120000,
};

const result = rescore(input);

const fixture = {
  note:
    "Generated by gen-fixture.mjs from scoring.mjs. Both the Lambda and the " +
    "client rescore.test.ts are checked against this. Regenerate with: " +
    "node infra/lambda/leaderboard/gen-fixture.mjs",
  input,
  expected: {
    stream,
    result,
  },
};

const out = join(here, "scoring.fixture.json");
writeFileSync(out, JSON.stringify(fixture, null, 2) + "\n");
console.log(`Wrote ${out} (stream=${stream.length} items, score=${result.score})`);
